Repository noviicee/Banque-De-Questions, pull requests merged in 2022-09, with the labels that each got.

#27 first commit check for hacktoberfest
  GoodtoSolve/Sort an array of 0s, 1s and 2s/Readme.md
  GoodtoSolve/Sort an array of 0s, 1s and 2s/sol.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022, code

#26 Update README.md with how to make a PR
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#28 added image smoother
  RandomQuestions/Image Smoother/Readme.md
  RandomQuestions/Image Smoother/sol.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022, code, needs-user-functionality
