Repository noviicee/Banque-De-Questions, pull requests merged in 2022-10, with the labels that each got.

#30 Contributors list fully automated
  .github/workflows/contributors.yaml
  .github/workflows/main.yml
  README.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#15 Added new questions
  RandomQuestions/Readme.md
  RandomQuestions/main.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022, code

#32 updated the already added interval-list-intersections
  RandomQuestions/Interval List Intersections/Readme.md
  RandomQuestions/Interval List Intersections/sol.py
  RandomQuestions/Readme.md
  RandomQuestions/main.py
Labels: enhancement, help wanted, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022, code, needs-user-functionality

#33 Added tom & jerry (a logical question)
  Logical/Tom and Jerry/Readme.md
  Logical/Tom and Jerry/sol.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022, code
